"""add

Revision ID: 3164bbaf8c56
Revises: 97bbb33d7a3c
Create Date: 2023-12-03 07:47:09.306942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3164bbaf8c56'
down_revision: Union[str, None] = '97bbb33d7a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=30), nullable=True, comment='name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=30), nullable=True, comment='name'),
    sa.Column('count', sa.Integer(), nullable=True, comment='count'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='user_id'),
    sa.Column('remarks', sa.String(length=100), nullable=True, comment='remarks'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memos_count'), 'memos', ['count'], unique=True)
    op.create_index(op.f('ix_memos_id'), 'memos', ['id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=30), nullable=True, comment='name'),
    sa.Column('genre_id', sa.Integer(), nullable=True, comment='genre_id'),
    sa.Column('deadline', sa.Integer(), nullable=True, comment='deadline'),
    sa.Column('count', sa.Integer(), nullable=True, comment='count'),
    sa.Column('message', sa.String(length=100), nullable=True, comment='message'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='user_id'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_genre_id'), 'stocks', ['genre_id'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.drop_index('ix_genles_id', table_name='genles')
    op.drop_table('genles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True, comment='name'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_genles_id', 'genles', ['id'], unique=False)
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_genre_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_memos_id'), table_name='memos')
    op.drop_index(op.f('ix_memos_count'), table_name='memos')
    op.drop_table('memos')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
