"""empty message

Revision ID: f01409c330e1
Revises: 6d460c2ba6b1
Create Date: 2024-01-25 14:26:25.736245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f01409c330e1'
down_revision: Union[str, None] = '6d460c2ba6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('message', mysql.VARCHAR(length=100), nullable=True, comment='message'))
    # ### end Alembic commands ###
